const mongoose = require("mongoose");

// Represents a scheduled irrigation event generated by the smart scheduling engine
const irrigationScheduleSchema = new mongoose.Schema({
  fieldName: { type: String, required: true },
  cropType: { type: String, required: true },
  soilType: { type: String, default: "loam" },
  areaHectares: { type: Number, default: 1 },
  scheduledDate: { type: Date, required: true },
  startTime: String,            // e.g., "06:00"
  endTime: String,              // e.g., "08:00"
  durationMinutes: Number,
  waterVolumeLiters: Number,
  priority: { type: String, enum: ["Critical", "High", "Medium", "Low"], default: "Medium" },
  status: { type: String, enum: ["scheduled", "completed", "skipped_rain", "skipped_sufficient_moisture", "cancelled"], default: "scheduled" },
  weatherConditions: {
    temperature: Number,
    humidity: Number,
    windSpeed: Number,
    rainProbability: Number,
  },
  et0: Number,                  // Reference evapotranspiration used for calculation
  cropET: Number,               // Crop evapotranspiration
  userId: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
}, { timestamps: true });

irrigationScheduleSchema.index({ userId: 1, scheduledDate: -1 });

module.exports = mongoose.models.IrrigationSchedule || mongoose.model("IrrigationSchedule", irrigationScheduleSchema);
