/**
 * Rich, intentionally realistic data for the demo experience.  Keeping the
 * shape close to the REST resources means screens can be switched to the API
 * without having to be redesigned later.
 */

export const DEMO_DATA_VERSION = 1;

export const FARM_ROLES = ["farmer", "manager", "agronomist", "admin"];
export const CROP_GROWTH_STAGES = [
  "Germination",
  "Vegetative",
  "Flowering",
  "Fruit development",
  "Maturity",
  "Harvest ready",
];
export const TASK_CATEGORIES = [
  "Planting",
  "Irrigation",
  "Scouting",
  "Nutrition",
  "Spraying",
  "Harvest",
  "Maintenance",
];
export const EXPENSE_CATEGORIES = [
  "Seeds",
  "Fertilizer",
  "Irrigation",
  "Labor",
  "Equipment",
  "Crop protection",
  "Fuel",
  "Other",
];

const isoRelativeToToday = (days, hour = 9, minute = 0) => {
  const date = new Date();
  date.setSeconds(0, 0);
  date.setDate(date.getDate() + days);
  date.setHours(hour, minute, 0, 0);
  return date.toISOString();
};

const localDateRelativeToToday = (days) => isoRelativeToToday(days, 12).slice(0, 10);

const recentMonthLabels = () => {
  const formatter = new Intl.DateTimeFormat("en", { month: "short" });
  const now = new Date();

  return Array.from({ length: 6 }, (_, index) => {
    const date = new Date(now.getFullYear(), now.getMonth() - 5 + index, 1);
    return formatter.format(date);
  });
};

/**
 * Build a fresh demo snapshot. Calling this instead of exporting a mutable
 * object ensures one user's local edits never leak into another session.
 */
export function createDemoFarmData() {
  const [apr, may, jun, jul, aug, sep] = recentMonthLabels();
  const now = new Date().toISOString();

  return {
    version: DEMO_DATA_VERSION,
    lastUpdated: now,
    activeFarmId: "farm-green-valley",
    profile: {
      id: "user-aisha-patel",
      name: "Aisha Patel",
      firstName: "Aisha",
      email: "aisha@greenvalley.farm",
      role: "farmer",
      phone: "+91 98765 43210",
      avatar: "AP",
      locale: "en-IN",
      timezone: "Asia/Kolkata",
      notificationPreferences: {
        push: true,
        email: true,
        sms: false,
        weeklyDigest: true,
      },
    },
    farms: [
      {
        id: "farm-green-valley",
        name: "Green Valley Farm",
        farmCode: "GVF-024",
        ownerId: "user-aisha-patel",
        location: {
          village: "Nashik",
          district: "Nashik",
          state: "Maharashtra",
          country: "India",
          coordinates: { latitude: 19.9975, longitude: 73.7898 },
        },
        totalAcres: 168.4,
        cultivatedAcres: 142.6,
        soilType: "Loamy black soil",
        irrigationSystem: "Precision drip irrigation",
        waterSource: "On-farm reservoir",
        sensorCount: 24,
        activeZones: 6,
        season: "Kharif 2026",
        sustainabilityScore: 91,
        waterSavingsPercent: 27,
        createdAt: isoRelativeToToday(-420),
        updatedAt: now,
      },
      {
        id: "farm-riverbend",
        name: "Riverbend Orchard",
        farmCode: "RBO-118",
        ownerId: "user-aisha-patel",
        location: {
          village: "Sinnar",
          district: "Nashik",
          state: "Maharashtra",
          country: "India",
          coordinates: { latitude: 19.8451, longitude: 73.9984 },
        },
        totalAcres: 42.8,
        cultivatedAcres: 36.2,
        soilType: "Well-drained sandy loam",
        irrigationSystem: "Micro-sprinklers",
        waterSource: "Borewell + rainwater harvesting",
        sensorCount: 8,
        activeZones: 3,
        season: "Perennial orchard",
        sustainabilityScore: 87,
        waterSavingsPercent: 19,
        createdAt: isoRelativeToToday(-680),
        updatedAt: now,
      },
    ],
    crops: [
      {
        id: "crop-tomato-north",
        farmId: "farm-green-valley",
        name: "Tomato",
        variety: "Arka Rakshak",
        field: "North Field",
        zone: "Zone A1",
        acreage: 24.5,
        plantedOn: localDateRelativeToToday(-51),
        expectedHarvest: localDateRelativeToToday(34),
        growthStage: "Flowering",
        stageProgress: 72,
        status: "healthy",
        healthScore: 92,
        moistureTarget: { min: 38, max: 54, unit: "%" },
        latestMoisture: 44,
        yieldForecastTonnes: 116.8,
        yieldChangePercent: 8.6,
        notes: "Flower set is strong. Maintain calcium feed before fruit fill.",
        color: "#F97316",
      },
      {
        id: "crop-maize-east",
        farmId: "farm-green-valley",
        name: "Maize",
        variety: "Pioneer 3396",
        field: "East Field",
        zone: "Zone B2",
        acreage: 38.2,
        plantedOn: localDateRelativeToToday(-67),
        expectedHarvest: localDateRelativeToToday(49),
        growthStage: "Vegetative",
        stageProgress: 64,
        status: "watch",
        healthScore: 78,
        moistureTarget: { min: 30, max: 45, unit: "%" },
        latestMoisture: 29,
        yieldForecastTonnes: 229.2,
        yieldChangePercent: 2.4,
        notes: "One low-moisture pocket in the south-east row needs attention.",
        color: "#EAB308",
      },
      {
        id: "crop-soy-west",
        farmId: "farm-green-valley",
        name: "Soybean",
        variety: "JS 335",
        field: "West Field",
        zone: "Zone C1",
        acreage: 31.8,
        plantedOn: localDateRelativeToToday(-59),
        expectedHarvest: localDateRelativeToToday(57),
        growthStage: "Flowering",
        stageProgress: 59,
        status: "healthy",
        healthScore: 88,
        moistureTarget: { min: 32, max: 47, unit: "%" },
        latestMoisture: 39,
        yieldForecastTonnes: 73.4,
        yieldChangePercent: 5.1,
        notes: "Canopy development is even across the monitored rows.",
        color: "#22C55E",
      },
      {
        id: "crop-grapes-orchard",
        farmId: "farm-riverbend",
        name: "Grapes",
        variety: "Thompson Seedless",
        field: "Orchard Block 2",
        zone: "Zone O2",
        acreage: 18.4,
        plantedOn: localDateRelativeToToday(-1480),
        expectedHarvest: localDateRelativeToToday(112),
        growthStage: "Fruit development",
        stageProgress: 46,
        status: "healthy",
        healthScore: 90,
        moistureTarget: { min: 34, max: 46, unit: "%" },
        latestMoisture: 41,
        yieldForecastTonnes: 174.8,
        yieldChangePercent: 4.8,
        notes: "Micro-sprinkler uniformity was checked this week.",
        color: "#8B5CF6",
      },
    ],
    soilReadings: [
      {
        id: "soil-north-latest",
        farmId: "farm-green-valley",
        cropId: "crop-tomato-north",
        field: "North Field",
        zone: "Zone A1",
        capturedAt: isoRelativeToToday(0, 8, 30),
        moisture: 44,
        ph: 6.7,
        temperature: 24.1,
        ec: 1.4,
        nitrogen: "adequate",
        phosphorus: "adequate",
        potassium: "high",
        status: "optimal",
      },
      {
        id: "soil-east-latest",
        farmId: "farm-green-valley",
        cropId: "crop-maize-east",
        field: "East Field",
        zone: "Zone B2",
        capturedAt: isoRelativeToToday(0, 8, 12),
        moisture: 29,
        ph: 6.4,
        temperature: 25.4,
        ec: 1.1,
        nitrogen: "low",
        phosphorus: "adequate",
        potassium: "adequate",
        status: "attention",
      },
      {
        id: "soil-west-latest",
        farmId: "farm-green-valley",
        cropId: "crop-soy-west",
        field: "West Field",
        zone: "Zone C1",
        capturedAt: isoRelativeToToday(0, 8, 18),
        moisture: 39,
        ph: 6.6,
        temperature: 23.7,
        ec: 1.2,
        nitrogen: "adequate",
        phosphorus: "low",
        potassium: "adequate",
        status: "watch",
      },
      {
        id: "soil-orchard-latest",
        farmId: "farm-riverbend",
        cropId: "crop-grapes-orchard",
        field: "Orchard Block 2",
        zone: "Zone O2",
        capturedAt: isoRelativeToToday(0, 8, 6),
        moisture: 41,
        ph: 6.9,
        temperature: 22.8,
        ec: 1.3,
        nitrogen: "adequate",
        phosphorus: "adequate",
        potassium: "adequate",
        status: "optimal",
      },
    ],
    soilTrends: [
      { date: localDateRelativeToToday(-6), moisture: 47, ph: 6.6, temperature: 22.5 },
      { date: localDateRelativeToToday(-5), moisture: 45, ph: 6.6, temperature: 23.0 },
      { date: localDateRelativeToToday(-4), moisture: 43, ph: 6.7, temperature: 24.2 },
      { date: localDateRelativeToToday(-3), moisture: 42, ph: 6.7, temperature: 24.6 },
      { date: localDateRelativeToToday(-2), moisture: 40, ph: 6.6, temperature: 25.1 },
      { date: localDateRelativeToToday(-1), moisture: 43, ph: 6.7, temperature: 24.4 },
      { date: localDateRelativeToToday(0), moisture: 44, ph: 6.7, temperature: 24.1 },
    ],
    weather: {
      id: "weather-nashik-current",
      farmId: "farm-green-valley",
      generatedAt: isoRelativeToToday(0, 8, 45),
      location: "Nashik, Maharashtra",
      current: {
        condition: "Partly cloudy",
        icon: "cloud-sun",
        temperature: 27,
        feelsLike: 29,
        humidity: 63,
        windKph: 13,
        uvIndex: 5,
        rainfallMm: 0,
        rainfallChance: 18,
        pressure: 1008,
      },
      forecast: [
        { date: localDateRelativeToToday(0), label: "Today", condition: "Partly cloudy", icon: "cloud-sun", low: 21, high: 29, precipitationChance: 18, rainfallMm: 0.4, windKph: 13 },
        { date: localDateRelativeToToday(1), label: "Tomorrow", condition: "Light rain", icon: "cloud-rain", low: 22, high: 28, precipitationChance: 68, rainfallMm: 6.8, windKph: 16 },
        { date: localDateRelativeToToday(2), label: "Thu", condition: "Thunderstorms", icon: "cloud-lightning", low: 21, high: 27, precipitationChance: 82, rainfallMm: 14.2, windKph: 24 },
        { date: localDateRelativeToToday(3), label: "Fri", condition: "Cloudy", icon: "cloud", low: 21, high: 28, precipitationChance: 39, rainfallMm: 2.1, windKph: 11 },
        { date: localDateRelativeToToday(4), label: "Sat", condition: "Sunny intervals", icon: "sun", low: 20, high: 30, precipitationChance: 15, rainfallMm: 0, windKph: 9 },
      ],
      advisory: "Pause foliar spraying on Thursday; thunderstorms may increase runoff risk.",
    },
    irrigationSchedules: [
      {
        id: "schedule-north-drip",
        farmId: "farm-green-valley",
        cropId: "crop-tomato-north",
        name: "North Field Drip",
        zone: "Zone A1",
        mode: "auto",
        enabled: true,
        days: ["Mon", "Wed", "Fri"],
        startTime: "05:30",
        durationMinutes: 42,
        threshold: 38,
        targetMoisture: 48,
        nextRun: isoRelativeToToday(1, 5, 30),
        lastRun: isoRelativeToToday(-1, 5, 30),
        estimatedLitres: 17800,
        todayAppliedLitres: 0,
        efficiencyScore: 94,
      },
      {
        id: "schedule-east-drip",
        farmId: "farm-green-valley",
        cropId: "crop-maize-east",
        name: "East Field Drip",
        zone: "Zone B2",
        mode: "auto",
        enabled: true,
        days: ["Tue", "Thu", "Sat"],
        startTime: "04:45",
        durationMinutes: 56,
        threshold: 32,
        targetMoisture: 40,
        nextRun: isoRelativeToToday(0, 18, 0),
        lastRun: isoRelativeToToday(-2, 4, 45),
        estimatedLitres: 24400,
        todayAppliedLitres: 0,
        efficiencyScore: 82,
      },
      {
        id: "schedule-west-drip",
        farmId: "farm-green-valley",
        cropId: "crop-soy-west",
        name: "West Field Drip",
        zone: "Zone C1",
        mode: "manual",
        enabled: true,
        days: ["Mon", "Thu"],
        startTime: "06:15",
        durationMinutes: 38,
        threshold: 33,
        targetMoisture: 42,
        nextRun: isoRelativeToToday(1, 6, 15),
        lastRun: isoRelativeToToday(-3, 6, 15),
        estimatedLitres: 13100,
        todayAppliedLitres: 0,
        efficiencyScore: 89,
      },
      {
        id: "schedule-orchard-sprinkler",
        farmId: "farm-riverbend",
        cropId: "crop-grapes-orchard",
        name: "Orchard Micro-sprinklers",
        zone: "Zone O2",
        mode: "auto",
        enabled: true,
        days: ["Tue", "Fri"],
        startTime: "05:00",
        durationMinutes: 48,
        threshold: 34,
        targetMoisture: 42,
        nextRun: isoRelativeToToday(2, 5, 0),
        lastRun: isoRelativeToToday(-2, 5, 0),
        estimatedLitres: 9600,
        todayAppliedLitres: 0,
        efficiencyScore: 91,
      },
    ],
    irrigationEvents: [
      {
        id: "event-west-previous",
        scheduleId: "schedule-west-drip",
        farmId: "farm-green-valley",
        action: "manual_run",
        startedAt: isoRelativeToToday(-3, 6, 15),
        durationMinutes: 38,
        appliedLitres: 13100,
        triggeredBy: "Aisha Patel",
      },
      {
        id: "event-north-previous",
        scheduleId: "schedule-north-drip",
        farmId: "farm-green-valley",
        action: "automatic_run",
        startedAt: isoRelativeToToday(-1, 5, 30),
        durationMinutes: 42,
        appliedLitres: 17800,
        triggeredBy: "Soil moisture rule",
      },
    ],
    tasks: [
      {
        id: "task-east-water",
        farmId: "farm-green-valley",
        cropId: "crop-maize-east",
        title: "Inspect low-moisture pocket",
        description: "Walk the south-east maize rows and verify the Zone B2 emitter line.",
        category: "Irrigation",
        priority: "high",
        dueAt: isoRelativeToToday(0, 15, 30),
        status: "pending",
        assignedTo: "Aisha Patel",
        createdAt: isoRelativeToToday(-1, 10),
      },
      {
        id: "task-tomato-calcium",
        farmId: "farm-green-valley",
        cropId: "crop-tomato-north",
        title: "Apply calcium nutrient feed",
        description: "Apply the approved calcium program before the next irrigation cycle.",
        category: "Nutrition",
        priority: "medium",
        dueAt: isoRelativeToToday(1, 8),
        status: "pending",
        assignedTo: "Ravi Kumar",
        createdAt: isoRelativeToToday(-2, 11),
      },
      {
        id: "task-soy-scouting",
        farmId: "farm-green-valley",
        cropId: "crop-soy-west",
        title: "Scout for soybean leaf miner",
        description: "Inspect 10 plants in each monitored row and add observations.",
        category: "Scouting",
        priority: "medium",
        dueAt: isoRelativeToToday(2, 7, 30),
        status: "pending",
        assignedTo: "Meera Shah",
        createdAt: isoRelativeToToday(-1, 9),
      },
      {
        id: "task-filter-complete",
        farmId: "farm-green-valley",
        cropId: null,
        title: "Clean reservoir inlet filter",
        description: "Completed during the scheduled maintenance round.",
        category: "Maintenance",
        priority: "low",
        dueAt: isoRelativeToToday(-1, 17),
        status: "completed",
        assignedTo: "Ravi Kumar",
        createdAt: isoRelativeToToday(-4, 12),
        completedAt: isoRelativeToToday(-1, 16, 40),
      },
      {
        id: "task-orchard-pruning",
        farmId: "farm-riverbend",
        cropId: "crop-grapes-orchard",
        title: "Review canopy training plan",
        description: "Confirm row-by-row canopy work allocation for Block 2.",
        category: "Maintenance",
        priority: "low",
        dueAt: isoRelativeToToday(4, 9),
        status: "pending",
        assignedTo: "Aisha Patel",
        createdAt: isoRelativeToToday(-1, 10),
      },
    ],
    alerts: [
      {
        id: "alert-east-moisture",
        farmId: "farm-green-valley",
        cropId: "crop-maize-east",
        title: "Low soil moisture in East Field",
        message: "Zone B2 is at 29%, below its 32% automation threshold.",
        type: "low_moisture",
        severity: "high",
        createdAt: isoRelativeToToday(0, 8, 14),
        resolved: false,
        actionLabel: "Water now",
      },
      {
        id: "alert-storm",
        farmId: "farm-green-valley",
        cropId: null,
        title: "Thunderstorm risk on Thursday",
        message: "Forecast rainfall may reach 14.2 mm with stronger wind gusts.",
        type: "weather",
        severity: "medium",
        createdAt: isoRelativeToToday(0, 8, 46),
        resolved: false,
        actionLabel: "View forecast",
      },
      {
        id: "alert-pest-scout",
        farmId: "farm-green-valley",
        cropId: "crop-soy-west",
        title: "Pest scouting recommended",
        message: "Leaf wetness and canopy humidity increase soybean leaf miner risk.",
        type: "pest_risk",
        severity: "medium",
        createdAt: isoRelativeToToday(-1, 16),
        resolved: false,
        actionLabel: "Open task",
      },
      {
        id: "alert-filter-cleared",
        farmId: "farm-green-valley",
        cropId: null,
        title: "Reservoir filter maintenance completed",
        message: "The inlet filter was cleaned and flow was restored.",
        type: "maintenance",
        severity: "low",
        createdAt: isoRelativeToToday(-1, 17),
        resolved: true,
        resolvedAt: isoRelativeToToday(-1, 17, 5),
        actionLabel: "View details",
      },
    ],
    expenses: [
      {
        id: "expense-seedlings",
        farmId: "farm-green-valley",
        cropId: "crop-tomato-north",
        category: "Seeds",
        vendor: "Mahindra Agri Solutions",
        amount: 48600,
        currency: "INR",
        incurredOn: localDateRelativeToToday(-48),
        note: "Tomato seedlings for North Field",
      },
      {
        id: "expense-fertilizer",
        farmId: "farm-green-valley",
        cropId: null,
        category: "Fertilizer",
        vendor: "Nashik Agro Mart",
        amount: 32800,
        currency: "INR",
        incurredOn: localDateRelativeToToday(-15),
        note: "Calcium nitrate and micronutrient blend",
      },
      {
        id: "expense-irrigation",
        farmId: "farm-green-valley",
        cropId: null,
        category: "Irrigation",
        vendor: "AquaFlow Services",
        amount: 18650,
        currency: "INR",
        incurredOn: localDateRelativeToToday(-9),
        note: "Drip line repairs and emitter replacements",
      },
      {
        id: "expense-labor",
        farmId: "farm-green-valley",
        cropId: null,
        category: "Labor",
        vendor: "Field operations",
        amount: 24100,
        currency: "INR",
        incurredOn: localDateRelativeToToday(-3),
        note: "Weeding and crop scouting crew",
      },
      {
        id: "expense-fuel",
        farmId: "farm-riverbend",
        cropId: "crop-grapes-orchard",
        category: "Fuel",
        vendor: "HP Fuel Station",
        amount: 6400,
        currency: "INR",
        incurredOn: localDateRelativeToToday(-5),
        note: "Orchard pump generator fuel",
      },
    ],
    analytics: {
      farmId: "farm-green-valley",
      period: "current_season",
      generatedAt: now,
      kpis: {
        forecastYieldTonnes: 419.4,
        yieldVsLastSeasonPercent: 8.1,
        waterUsedLitres: 281400,
        waterSavedLitres: 104200,
        waterSavingsPercent: 27,
        operatingExpense: 124150,
        expenseVsBudgetPercent: 68,
        averageCropHealth: 86,
      },
      yieldSeries: [
        { month: apr, actual: 42, forecast: 46, baseline: 40 },
        { month: may, actual: 54, forecast: 57, baseline: 48 },
        { month: jun, actual: 59, forecast: 63, baseline: 55 },
        { month: jul, actual: 72, forecast: 75, baseline: 64 },
        { month: aug, actual: 81, forecast: 86, baseline: 73 },
        { month: sep, actual: 91, forecast: 98, baseline: 82 },
      ],
      moistureSeries: [
        { day: "Mon", tomato: 46, maize: 34, soybean: 41 },
        { day: "Tue", tomato: 44, maize: 32, soybean: 40 },
        { day: "Wed", tomato: 43, maize: 30, soybean: 39 },
        { day: "Thu", tomato: 45, maize: 29, soybean: 38 },
        { day: "Fri", tomato: 44, maize: 32, soybean: 40 },
        { day: "Sat", tomato: 46, maize: 35, soybean: 41 },
        { day: "Sun", tomato: 44, maize: 33, soybean: 39 },
      ],
      waterSeries: [
        { week: "W1", used: 68600, saved: 19800 },
        { week: "W2", used: 72200, saved: 23500 },
        { week: "W3", used: 69100, saved: 26100 },
        { week: "W4", used: 71500, saved: 34800 },
      ],
      expenseSummary: [
        { category: "Seeds", amount: 48600, color: "#D97706" },
        { category: "Fertilizer", amount: 32800, color: "#65A30D" },
        { category: "Labor", amount: 24100, color: "#0EA5E9" },
        { category: "Irrigation", amount: 18650, color: "#14B8A6" },
      ],
      cropPerformance: [
        { cropId: "crop-tomato-north", crop: "Tomato", health: 92, forecastYield: 116.8, marginPercent: 34, status: "Ahead of plan" },
        { cropId: "crop-maize-east", crop: "Maize", health: 78, forecastYield: 229.2, marginPercent: 26, status: "Monitor moisture" },
        { cropId: "crop-soy-west", crop: "Soybean", health: 88, forecastYield: 73.4, marginPercent: 29, status: "On track" },
      ],
      insights: [
        {
          id: "insight-water",
          title: "Water efficiency is improving",
          description: "Automation has saved an estimated 104,200 L this season, 27% better than last season.",
          tone: "positive",
        },
        {
          id: "insight-maize",
          title: "Maize needs a targeted irrigation pass",
          description: "One Zone B2 reading is below the moisture threshold; correct it today to protect yield potential.",
          tone: "action",
        },
        {
          id: "insight-weather",
          title: "Rain may reduce Thursday demand",
          description: "Forecast rainfall could satisfy part of the next West Field cycle. Review auto schedule after the storm.",
          tone: "neutral",
        },
      ],
    },
    activity: [
      {
        id: "activity-sync",
        type: "sensor",
        title: "24 field sensors synced",
        detail: "Latest readings arrived from Green Valley Farm.",
        occurredAt: isoRelativeToToday(0, 8, 45),
      },
      {
        id: "activity-task",
        type: "task",
        title: "Reservoir filter maintenance completed",
        detail: "Ravi marked the maintenance task complete.",
        occurredAt: isoRelativeToToday(-1, 16, 40),
      },
      {
        id: "activity-irrigation",
        type: "irrigation",
        title: "North Field irrigation completed",
        detail: "17,800 L applied automatically in 42 minutes.",
        occurredAt: isoRelativeToToday(-1, 6, 12),
      },
    ],
  };
}

export function cloneDemoData(data = createDemoFarmData()) {
  return JSON.parse(JSON.stringify(data));
}

